branches:
  only:
  - master

language: node_js
node_js:
  - "10"

script: npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: d205edcca78ea82683ed6eb3595b100d5cfd3ae1
  local-dir: build
  keep-history: true
  on:
branch: master
