branches:
  only:
  - master

language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn

script:
  - yarn lint
  - yarn build --base-href /give-me-the-rulebook/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/my-awesome-project
  on:
branch: master
