branches:
  only:
  - master

language: node_js
node_js:
  - "10"

script: npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: dce13e36e9e5d497fd5e3793aaab2a763c3cc13d
  local-dir: build
  keep-history: true
  on:
branch: master
