import {DiceBonus} from "./Dice/DiceBonus";

export const BonusAttackBonusGridHigh: DiceBonus[] = [
    new DiceBonus(1),
    new DiceBonus(2),
    new DiceBonus(3),
    new DiceBonus(4),
    new DiceBonus(5),
    new DiceBonus(6, 1),
    new DiceBonus(7, 2),
    new DiceBonus(8, 3),
    new DiceBonus(9, 4),
    new DiceBonus(10, 5),
    new DiceBonus(11, 6, 1),
    new DiceBonus(12, 7, 2),
    new DiceBonus(13, 8, 3),
    new DiceBonus(14, 9, 4),
    new DiceBonus(15, 10, 5),
    new DiceBonus(16, 11, 6, 1),
    new DiceBonus(17, 12, 7, 2),
    new DiceBonus(18, 13, 8, 3),
    new DiceBonus(19, 14, 9, 4),
    new DiceBonus(20, 15, 10, 5)
];

export const BonusAttackBonusGridMedium: DiceBonus[] = [
    new DiceBonus(0),
    new DiceBonus(1),
    new DiceBonus(2),
    new DiceBonus(3),
    new DiceBonus(3),
    new DiceBonus(4),
    new DiceBonus(5),
    new DiceBonus(6, 1),
    new DiceBonus(6, 1),
    new DiceBonus(7, 2),
    new DiceBonus(8, 3),
    new DiceBonus(9, 4),
    new DiceBonus(9, 4),
    new DiceBonus(10, 5),
    new DiceBonus(11, 6, 1),
    new DiceBonus(12, 7, 2),
    new DiceBonus(12, 7, 2),
    new DiceBonus(13, 8, 3),
    new DiceBonus(14, 9, 4),
    new DiceBonus(15, 10, 5)
];

export const BonusAttackBonusGridLow: DiceBonus[] = [
    new DiceBonus(0),
    new DiceBonus(1),
    new DiceBonus(1),
    new DiceBonus(2),
    new DiceBonus(2),
    new DiceBonus(3),
    new DiceBonus(3),
    new DiceBonus(4),
    new DiceBonus(4),
    new DiceBonus(5),
    new DiceBonus(5),
    new DiceBonus(6, 1),
    new DiceBonus(6, 1),
    new DiceBonus(7, 2),
    new DiceBonus(7, 2),
    new DiceBonus(8, 3),
    new DiceBonus(8, 3),
    new DiceBonus(9, 4),
    new DiceBonus(9, 4),
    new DiceBonus(10, 5),
];